spring:
  datasource:
    url: jdbc:mysql://localhost:3306/healthcare_management
    username: healthbridge_staff
    password: healthbridge
    driver-class-name: com.mysql.cj.jdbc.Driver
    -mode: always
jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      show_sql: true  
